4 workflow run results
Update Python setup in GitHub Actions workflow
.github/workflows/main.yml #3: Commit 143bff4 pushed by akbarbinhabib-dotcom
main	
1 minute ago
 Failure
Update Python setup in GitHub Actions workflow
.github/workflows/main07.yml #2: Commit 143bff4 pushed by akbarbinhabib-dotcom
main	
1 minute ago
 -1s
Add AWS SAM deployment workflow
.github/workflows/main.yml #2: Commit 7107f04 pushed by akbarbinhabib-dotcom
main	
2 minutes ago
 Failure
Add AWS SAM deployment workflow
.github/workflows/main07.yml #1: Commit 7107f04 pushed by akbarbinhabib-dotcom
main	
2 minutes ago
 Failure
